language: node_js
node_js:
- 16.18.1
env:
  global:
  - secure: mQg92G6gefjtuvhptpM/S/70KgVD00oDI7Hyc67fqIOoeLX0NK1EzhSnvZVhy9H8awWFb4PGul4YTB4+s+ghMtKzlZKLdfmILupQ4rPTn+EWs8M0V3ivLun/o4BjpU31Ac/anqDa7GwsmaYH7SkylQVq7Zi652RcnGu0Mvp7lR4s36VhUGw5HUjwmJ2IO1Jg6NJeawbjKS1bkc20DFQn5dR2eZDo5qMDCH1OkAL+kWYzwePt5L+D0AeoA9GUR3Dnbw6oMom2ieg/rfDFjtYH3YR9v/+skusrJJrLtXFfdGWj50xqVKeVijXDh0krlwoIz2ovh6n6kW535m/qv1wxmnueUwK7KfUqNoD1n5QQ9HOo7214nUqrybgyrMuF2zKab0vZ53Krre5h7IYKytw3sCe3j+Rcv8hH1Zf/uy4OdL50S7xAodi1wQihvQHzShpezOOqPYxQP3E00R5uoOMhImFCOXRuvyKlGWmixsIbZ9r4KB8sJS2pZaGgXQ1D0aLf1FRSkEUgpoY5t21NpyAToWaWhEV6dljcyWgYgHJg0k+NQscXUwIIcIKa+rYH0sT8D7DqbpRwAjl8tr7Oo5k8ov9kbR70xZN56aWfjFr7JpXK/vsLiQZTuIi62bdLQn9f++jek2bPl+wVkBrLvcD7vrkVwh2BqZVf81I7OIFVGE8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
    --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
